### ISSUE TITLE
Add more Jail locations

### ISSUE THREAD

**Issue by HumanTree92** [ESX-PUBLIC/esx_jail#13]
For instance when you jail 2 players they r always put in the same cell. Add the ability to add more then 1 location. Like if someone moved the jail to mission row pd. You can setup all the cells.

**Comment by ElPumpo** [comment]
I want to move away from this 'cell'. I was thinking of using the outside area as a part of the prison.

**Comment by Ultrunz** [comment]
Thats a good idea. But you'd need to include a map that blocks off the exits because they could all run out. I was on a server that did a similar thing.

**Comment by ElPumpo** [comment]
Not gonna happen, no cells here

**Comment by TanguyOrtegat** [comment]
adding more locations won't be done, we do provide basic scripts that you can enhance with as many locations or other functions as you want
