### ISSUE TITLE
policejob jailing

### ISSUE THREAD

**Issue by oogienl** [ESX-PUBLIC/esx_jail#18]
im trying to get jailing to work so that i dont have to make all my cops in the server an admin, but im getting errors and it doesnt work. perhaps someone can see what im doing wrong because i followed the instructions with no succes.

Error running call reference function for resource esx_policejob: citizen:/scripting/lua/scheduler.lua:351: @es_extended/locale.lua:8: bad argument #2 to 'format' (no value)
stack traceback:
[C]: in function 'string.format'
@es_extended/locale.lua:8: in function '_'
@es_extended/locale.lua:20: in function '_U'
client/main.lua:847: in function 'JailPlayer'
client/main.lua:539: in upvalue 'ref'
citizen:/scripting/lua/scheduler.lua:337: in function <citizen:/scripting/lua/scheduler.lua:336>
[C]: in function 'xpcall'
citizen:/scripting/lua/scheduler.lua:336: in function <citizen:/scripting/lua/scheduler.lua:335>
stack traceback:
[C]: in function 'error'
citizen:/scripting/lua/scheduler.lua:351: in function <citizen:/scripting/lua/scheduler.lua:322>
Error running system event handling function for resource esx_menu_default: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: citizen:/scripting/lua/MessagePack.lua:830: missing bytes
stack traceback:
[C]: in function 'error'
citizen:/scripting/lua/MessagePack.lua:830: in method 'underflow'
citizen:/scripting/lua/MessagePack.lua:465: in field 'any'
citizen:/scripting/lua/MessagePack.lua:860: in field 'unpack'
citizen:/scripting/lua/scheduler.lua:563: in field 'submit'
client/main.lua:53: in upvalue 'handler'
citizen:/scripting/lua/scheduler.lua:175: in function <citizen:/scripting/lua/scheduler.lua:174>
stack traceback:
[C]: in function 'error'
citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>
[C]: in function 'coroutine.resume'
citizen:/scripting/lua/scheduler.lua:34: in field 'CreateThreadNow'
citizen:/scripting/lua/scheduler.lua:174: in function <citizen:/scripting/lua/scheduler.lua:138>

these are in my policejob main.lua
https://gyazo.com/2f5dced0065d9ebeeb475e811d051eb5

https://gyazo.com/2f5dced0065d9ebeeb475e811d051eb5

**Comment by ElPumpo** [comment]
Same as #19
