### ISSUE TITLE
Issue with police jailing

### ISSUE THREAD

**Issue by DethProofSavage** [ESX-PUBLIC/esx_jail#25]
When i add the code lines to the esx_policejob to get this to work it doesn't show an error but it won't let me open the F6 menu as PD

**Comment by ponduzn** [comment]
> When i add the code lines to the esx_policejob to get this to work it doesn't show an error but it won't let me open the F6 menu as PD

Same happens here, if you paste it into the bottom of the  file, i think you have to place the code specific places, not sure though. would like some help on this aswell.

**Comment by DethProofSavage** [comment]
> > When i add the code lines to the esx_policejob to get this to work it doesn't show an error but it won't let me open the F6 menu as PD
> 
> Same happens here, if you paste it into the bottom of the file, i think you have to place the code specific places, not sure though. would like some help on this aswell.

Well i got it working since i posted this issue

**Comment by ponduzn** [comment]
> > > When i add the code lines to the esx_policejob to get this to work it doesn't show an error but it won't let me open the F6 menu as PD
> > 
> > 
> > Same happens here, if you paste it into the bottom of the file, i think you have to place the code specific places, not sure though. would like some help on this aswell.
> 
> Well i got it working since i posted this issue. All i changed from what the post said to add to esx_policejob to get it working was put
> 
> ```
> 	                                elseif action == 'jail' then
>                                 		JailPlayer(GetPlayerServerId(closestPlayer))
> ```
> under
> 
> ```
> 					elseif action == 'unpaid_bills' then
> 						OpenUnpaidBillsMenu(closestPlayer)
> ```
> instead of adding
> 
> ```
> 		if data2.current.value == 'jail' then
> 			JailPlayer(GetPlayerServerId(closestPlayer))
> 		end
> ```

Thanks man, works for me too, cheers for the update!

**Comment by DethProofSavage** [comment]
No problem dude just figured i'd share what fixed it for me
