### ISSUE TITLE
Jail menu option for policejob does not work

### ISSUE THREAD

**Issue by Duqino** [ESX-PUBLIC/esx_jail#30]
Hello,

I cant get the option to work. I got so far that it will open the menu to enter the time the player must b in jail. But nothing happens.

[![Screenshot from Gyazo](https://gyazo.com/98c9eb8c2a8ac2f4aa3d5c878176ddb5/raw)](https://gyazo.com/98c9eb8c2a8ac2f4aa3d5c878176ddb5)
[![Screenshot from Gyazo](https://gyazo.com/e3c7ab326fe73bb21ff84a74589203cf/raw)](https://gyazo.com/e3c7ab326fe73bb21ff84a74589203cf)

and at the bottem 

[![Screenshot from Gyazo](https://gyazo.com/3f9b9e90bb843769a43f68452193701f/raw)](https://gyazo.com/3f9b9e90bb843769a43f68452193701f)

**Comment by erroljohnyatar** [comment]
You have to change `action=='jail'` in line 58 to `action=='gsr_test'`
